apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter-servicemonitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  endpoints:
    - port: metrics
      interval: 30s
