apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wordpress-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: wordpress-legacy
  endpoints:
    - port: http
      interval: 30s
